# Generated by Django 6.0 on 2026-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('purpose', models.JSONField()),
                ('other_purpose', models.CharField(blank=True, max_length=255)),
                ('visit_date', models.DateField()),
                ('facility_cleanliness', models.PositiveSmallIntegerField()),
                ('layout_flow', models.PositiveSmallIntegerField()),
                ('food_safety', models.PositiveSmallIntegerField()),
                ('employee_hygiene', models.PositiveSmallIntegerField()),
                ('temperature_control', models.PositiveSmallIntegerField()),
                ('documentation', models.PositiveSmallIntegerField()),
                ('responsiveness', models.PositiveSmallIntegerField()),
                ('overall_impression', models.PositiveSmallIntegerField()),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
