# Generated by Django 6.0 on 2026-01-21 12:31

import signature_pad.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0002_purposeoption_alter_visitorfeedback_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('team_to_contact', models.CharField(choices=[('sales', 'Sales'), ('imports', 'Imports'), ('exports', 'Exports'), ('procurement', 'Procurement'), ('other', 'Other')], max_length=20)),
                ('other_team_description', models.CharField(blank=True, help_text="Required only if 'Other' is selected", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visitorfeedback',
            name='signature',
            field=signature_pad.fields.SignaturePadField(blank=True, null=True),
        ),
    ]
