# Generated by Django 6.0 on 2026-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0004_oceanospinnerdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='fifteen_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='i_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='mystery_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='ten_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='thirty_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='twenty_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
