# Generated by Django 6.0 on 2026-01-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0005_oceanospinnerdraw_fifteen_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='fifteen_percentage',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='free_delivery',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='i_phone',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='mystery_gift',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='ten_percentage',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='thirty_percentage',
        ),
        migrations.RemoveField(
            model_name='oceanospinnerdraw',
            name='twenty_percentage',
        ),
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='reward',
            field=models.CharField(blank=True, choices=[('', 'No Reward'), ('i_phone', 'iPhone'), ('mystery_gift', 'Mystery Gift'), ('ten_percentage', '10% Discount'), ('fifteen_percentage', '15% Discount'), ('twenty_percentage', '20% Discount'), ('thirty_percentage', '30% Discount'), ('free_delivery', 'Free Delivery')], default='', help_text='Only one reward can be active per entry', max_length=20),
        ),
    ]
