# Generated by Django 6.0 on 2026-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0006_remove_oceanospinnerdraw_fifteen_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceanospinnerdraw',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
