# Generated by Django 6.0 on 2026-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_interface', '0007_oceanospinnerdraw_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanospinnerdraw',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='oceanospinnerdraw',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='oceanospinnerdraw',
            name='reward',
            field=models.CharField(blank=True, choices=[('', 'No Reward'), ('oceano_hamper', 'Oceano Hamper - Worth 500AED'), ('mystery_gift', 'Oceano Mystery Gift - Worth 300AED'), ('ten_percentage', '10% Off On Entire Oceano Range'), ('fifteen_percentage', '15% Off On Oceano Smoked Range'), ('twenty_percentage', '20% Off On Oceano Fresh Range'), ('thirty_percentage', '30% Off On Oceano Sushi'), ('free_delivery', 'Free Delivery')], default='', help_text='Only one reward can be active per entry', max_length=20),
        ),
    ]
